[project]
name = "comorbidipy"
description = "Python package to calculate comorbidity scores and other clinical risk scores."
readme = "README.md"
license = { file = "LICENSE" }
keywords = [
    "comorbidity",
    "clinical risk scores",
    "healthcare",
    "data analysis",
]
dynamic = ["version"]
authors = [{ name = "vvcb" }]
requires-python = ">=3.13"
dependencies = ["polars>=1.27.1", "typer>=0.15.2"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.scripts]
comorbidipy = "comorbidipy.cli:main"
cmpy = "comorbidipy.cli:main"

[project.urls]
Homepage = "https://github.com/vvcb/comorbidipy"
Repsoitory = "https://github.com/vvcb/comorbidipy"
Issues = "https://github.com/vvcb/comorbidipy/issues"
Documentation = "https://vvcb.github.io/comorbidipy"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/comorbidipy/__init__.py"

[dependency-groups]
dev = [
    "jupyterlab>=4.4.0",
    "mkdocs>=1.6.1",
    "mkdocs-git-authors-plugin>=0.9.5",
    "mkdocs-material>=9.6.12",
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "ruff>=0.11.6",
]
[tool.ruff]

# Enable pycodestyle (E), Pyflakes (F), isort (I), and more
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]

ignore = [
    "PD901", # Avoid using generic dataframe names like df
]


# Allow autofix for all enabled rules (when `--fix` is provided)
fixable = ["ALL"]
unfixable = []

# Exclude files and directories
exclude = [".git", ".venv", "__pycache__", "build", "dist"]

# Same as Black
line-length = 88

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10
target-version = "py310"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.isort]
known-third-party = []
known-first-party = ["your_package_name"]

[tool.ruff.pydocstyle]
convention = "google" # Google-style docstrings

[tool.ruff.per-file-ignores]
"tests/**/*" = ["S101", "ANN"] # Allow assert in tests, skip annotation checks

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
